# Generated by Django 2.1.3 on 2018-12-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0002_agentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentnotification',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
