# Generated by Django 2.1.3 on 2018-12-02 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='executive',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='executive_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
