# Generated by Django 2.1.3 on 2018-12-02 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20181202_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
