# Generated by Django 2.1 on 2018-11-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userpage', '0005_auto_20181111_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('agentid', models.CharField(default='a', max_length=50)),
                ('employeeid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('employeename', models.CharField(max_length=50)),
                ('employeephone', models.CharField(max_length=20)),
                ('employeeemail', models.CharField(max_length=50)),
                ('employeeaddress', models.CharField(max_length=500)),
                ('employeeaadhar', models.CharField(max_length=50)),
            ],
        ),
    ]
