# Generated by Django 2.1.3 on 2018-12-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_cans',
            field=models.IntegerField(default=0),
        ),
    ]
