# Generated by Django 2.1.3 on 2018-12-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_number_of_cans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_of_cans',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
