# Generated by Django 2.1.3 on 2018-12-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181213_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='only_online',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
