# Generated by Django 2.1.2 on 2018-11-18 12:39

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181118_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.upload_path_handler),
        ),
    ]
