# Generated by Django 2.1.3 on 2018-12-05 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='my_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('1', 'COD')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
