# Generated by Django 2.1.2 on 2018-11-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181117_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('0', 'FAILED'), ('X', 'CANCELLED'), ('W', 'CANCEL REQUESTED'), ('1', 'PLACED'), ('2', 'CONFIRMED'), ('3', 'OUT FOR DELIVERY'), ('4', 'DELIVERED')], default='1', max_length=1),
        ),
    ]
