# Generated by Django 2.1.3 on 2018-12-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181205_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='my_date',
            new_name='preffered_time',
        ),
    ]
