# Generated by Django 2.1.3 on 2018-12-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181205_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='preferred_time',
            field=models.TimeField(blank=True),
        ),
    ]
