# Generated by Django 2.1.3 on 2018-12-07 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20181205_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='id',
        ),
        migrations.AlterField(
            model_name='tracking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
