# Generated by Django 2.1.3 on 2018-12-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20181207_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
