# Generated by Django 2.1.3 on 2018-12-07 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20181207_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.Order'),
        ),
    ]
