# Generated by Django 2.1.3 on 2018-12-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_subscription_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription',
            field=models.CharField(max_length=30),
        ),
    ]
