# Generated by Django 2.1.3 on 2018-12-07 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20181207_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
