# Generated by Django 2.1.3 on 2018-12-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20181208_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
