# Generated by Django 2.1.3 on 2018-12-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20181212_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('0', 'FAILED'), ('X', 'CANCELLED'), ('W', 'CANCEL REQUESTED'), ('1', 'PLACED'), ('2', 'CONFIRMED'), ('3', 'OUT FOR DELIVERY'), ('4', 'DELIVERED'), ('P', 'PROCESSING')], default='1', max_length=1),
        ),
    ]
