# Generated by Django 2.1.3 on 2018-12-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20181212_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('1', 'COD'), ('2', 'ONLINE'), ('3', 'SUBSCRIPTION')], default='1', max_length=1),
        ),
    ]
