# Generated by Django 2.1.3 on 2018-12-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20181212_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
