# Generated by Django 2.1.2 on 2018-11-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_agent_customer_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fullname',
            field=models.CharField(default='abcd', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'customer'), (2, 'agent'), (3, 'executive')]),
        ),
    ]
