# Generated by Django 2.1.2 on 2018-11-14 20:53

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import userAuth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_auto_20181114_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='area',
            field=models.CharField(choices=[('600018', 'Abhiramapuram'), ('600020', 'Adyar'), ('600040', 'Anna Nagar')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='agent',
            name='fullname',
            field=models.CharField(default='hanimohammed', max_length=50, validators=[django.core.validators.RegexValidator('^[ a-zA-Z]*$', 'Only alphabets are allowed.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+919840794287', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, upload_to=userAuth.models.upload_path_handler),
        ),
        migrations.AddField(
            model_name='agent',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='executive',
            name='complaints_queue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executive',
            name='fullname',
            field=models.CharField(default='hanimohamm', max_length=50, validators=[django.core.validators.RegexValidator('^[ a-zA-Z]*$', 'Only alphabets are allowed.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executive',
            name='photo',
            field=models.ImageField(blank=True, upload_to=userAuth.models.upload_path_handler),
        ),
    ]
