# Generated by Django 2.1.2 on 2018-11-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_auto_20181105_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'customer'), (2, 'agent'), (3, 'executive'), (5, 'admin')], default=5),
        ),
    ]
