# Generated by Django 2.1.2 on 2018-11-07 14:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_auto_20181106_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=9840794287, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
    ]
