# Generated by Django 2.1.2 on 2018-11-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='photo',
        ),
    ]
