# Generated by Django 2.1.2 on 2018-11-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0007_item_notification_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
