# Generated by Django 2.1.2 on 2018-11-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0009_auto_20181117_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notifier',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
