# Generated by Django 2.1 on 2018-11-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.PositiveIntegerField(default=0)),
                ('itemname', models.CharField(max_length=100)),
                ('itemcost', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cans', models.PositiveIntegerField(default=0)),
                ('bottles', models.PositiveIntegerField(default=0)),
                ('tissues', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
