# Generated by Django 2.1 on 2018-11-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_auto_20181101_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('billingaddress', models.CharField(max_length=200)),
                ('billingdate', models.DateTimeField(auto_now_add=True)),
                ('billingamount', models.PositiveIntegerField(default=0)),
                ('billingtype', models.CharField(max_length=50)),
                ('orderplaced', models.BooleanField(default=False)),
                ('orderstatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemname',
            field=models.CharField(max_length=50),
        ),
    ]
