# Generated by Django 2.1 on 2018-11-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_auto_20181110_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'get_latest_by': 'date'},
        ),
    ]
